service: holdr-mumbaianalytics
frameworkVersion: '3'	
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  stage: dev
  region: us-west-2
  stackName: holdr-mumbai-analytics
  runtime: nodejs14.x

functions:
  getPoolCount:
    handler: src/handlers.getPoolCountHandler
    events:
      - http:
          path: pools/poolcount
          method: get
          cors: true
  getLPCount:
    handler: src/handlers.getLPCountHandler
    events:
      - http:
          path: pools/lpcount
          method: get
          cors: true
  getTVL:
    handler: src/handlers.getTVLHandler
    events:
      - http:
          path: pools/tvl
          method: get
          cors: true
  getTokenHolders:
    handler: src/handlers.getTokenHoldersHandler
    events:
      - http:
          path: governance/tokenholders
          method: get
          cors: true
  getTokensMinted:
    handler: src/handlers.getTokensMintedHandler
    events:
      - http:
          path: governance/tokensminted
          method: get
          cors: true
  getTokenHolderAndLPCount:
    handler: src/handlers.getTokenHolderAndLPCountHandler
    events:
      - http:
          path: governance/tokenholdersandlp
          method: get
          cors: true
  get24HSwapVolume:
    handler: src/handlers.get24HSwapVolumeHandler
    events:
      - http:
          path: exchange/24hvolume
          method: get
          cors: true
  get7DSwapVolume:
    handler: src/handlers.get7DSwapVolumeHandler
    events:
      - http:
          path: exchange/7dvolume
          method: get
          cors: true
  getTotalVeHLDR:
    handler: src/handlers.getTotalVeHLDRHandler
    events:
      - http:
          path: vehldr/totalvehldr
          method: get
          cors: true
  getTotalHPT:
    handler: src/handlers.getTotalHPTHandler
    events:
      - http:
          path: vehldr/totalhpt
          method: get
          cors: true
  getHPTLocked:
    handler: src/handlers.getHPTLockedHandler
    events:
      - http:
          path: vehldr/lockedhpt
          method: get
          cors: true
  getAverageLockTime:
    handler: src/handlers.getAverageLockTimeHandler
    events:
      - http:
          path: vehldr/locktime
          method: get
          cors: true
  getPercentageHPTLocked:
    handler: src/handlers.getPercentageHPTLockedHandler
    events:
      - http:
          path: vehldr/percentagehptlocked
          method: get
          cors: true

custom:
  customDomain:
    certificateName: holdr.fi
    domainName: api.holdr.fi
    basePath: 'analytics-mumbai'
    stage: ${self:provider.stage}
    createRoute53Record: true
