service: holdr-lbp-api
frameworkVersion: '3'	
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-west-2
  stackName: holdr-lbp-api
  runtime: nodejs14.x

functions:
  getLBPTimeRemaining:
    handler: src/handlers.getLBPTimeRemainingHandler
    events:
      - http:
          path: time
          method: get
          cors: true
  getLBPprice:
    handler: src/handlers.getLBPPriceHandler
    events:
      - http:
          path: price
          method: get
          cors: true
