service: solace-swap-bribes
frameworkVersion: '3'	
useDotenv: true

provider:
  name: aws
  region: us-west-2
  stackName: solace-swap-bribes
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - 'arn:aws:s3:::${env:BUCKET_NAME}/*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:UpdateItem
        - dynamodb:UpdateTable
        - dynamodb:DeleteItem
      Resource: 
        - 'arn:aws:s3:::${env:TABLE_NAME}/*'

functions:
  parseBribeDeposits:
    handler: src/handlers.parseBribeDepositsHandler
  createMerkleTree:
    handler: src/handlers.createMerkleTreeHandler
  getGaugeToProposalMap:
    handler: src/handlers.getGaugeToProposalMapHandler
  createEmptyS3Objects:
    handler: src/handlers.createEmptyS3ObjectsHandler
  getUpdateRewardsMetadataParameters:
    handler: src/handlers.getUpdateRewardsMetadataParametersHandler
  getClaimParameters:
    handler: src/handlers.getClaimParametersHandler
    events:
      - http:
          path: claims
          method: get
          cors: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}

    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${env:TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: voter
            AttributeType: S
          - AttributeName: token
            AttributeType: S
          - AttributeName: bribeId
            AttributeType: S
        KeySchema:
          - AttributeName: voter
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: BribeIdIndex
            KeySchema:
              - AttributeName: bribeId
                KeyType: HASH
              - AttributeName: voter
                KeyType: RANGE
            Projection:
              ProjectionType: 'KEYS_ONLY'
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          # Would like to add the following global secondary index (GSI), but apparently AWS doesn't let us change an existing DynamoDB table to add more than 1 global secondary index, we can only create a new table with more than 1 global secondary index. So this secondary GSI is a nice-to-have, not a must have for the bribe table.
          # - IndexName: TokenIndex
          #   KeySchema:
          #     - AttributeName: token
          #       KeyType: HASH
          #     - AttributeName: voter
          #       KeyType: RANGE
          #   Projection:
          #     ProjectionType: 'KEYS_ONLY'
          #   ProvisionedThroughput:
          #     ReadCapacityUnits: 5
          #     WriteCapacityUnits: 5
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        BillingMode: PROVISIONED

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-dynamodb-autoscaling
