service: holdr-analytics
frameworkVersion: '3'	
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  stage: dev
  region: us-west-2
  stackName: holdr-analytics
  runtime: nodejs14.x

functions:
  getPoolCount:
    handler: src/handlers.getPoolCountHandler
    events:
      - http:
          path: poolCount
          method: get
          cors: true
  getLPCount:
    handler: src/handlers.getLPCountHandler
    events:
      - http:
          path: lpCount
          method: get
          cors: true
  getTVL:
    handler: src/handlers.getTVLHandler
    events:
      - http:
          path: tvl
          method: get
          cors: true
  getTokenHolders:
    handler: src/handlers.getTokenHoldersHandler
    events:
      - http:
          path: tokenholders
          method: get
          cors: true
  getTokensMinted:
    handler: src/handlers.getTokensMintedHandler
    events:
      - http:
          path: tokensMinted
          method: get
          cors: true
  getTokenHolderAndLPCount:
    handler: src/handlers.getTokenHolderAndLPCountHandler
    events:
      - http:
          path: tokenholderAndLP
          method: get
          cors: true
  get24HSwapVolume:
    handler: src/handlers.get24HSwapVolumeHandler
    events:
      - http:
          path: swapVolume24H
          method: get
          cors: true
  get7DSwapVolume:
    handler: src/handlers.get7DSwapVolumeHandler
    events:
      - http:
          path: swapVolume7D
          method: get
          cors: true
  getTotalVeHLDR:
    handler: src/handlers.getTotalVeHLDRHandler
    events:
      - http:
          path: totalvehldr
          method: get
          cors: true
  getTotalHPT:
    handler: src/handlers.getTotalHPTHandler
    events:
      - http:
          path: totalHPT
          method: get
          cors: true
  getHPTLocked:
    handler: src/handlers.getHPTLockedHandler
    events:
      - http:
          path: HPTLocked
          method: get
          cors: true
  getAverageLockTime:
    handler: src/handlers.getAverageLockTimeHandler
    events:
      - http:
          path: averageLockTime
          method: get
          cors: true
  getPercentageHPTLocked:
    handler: src/handlers.getPercentageHPTLockedHandler
    events:
      - http:
          path: percentageHPTlocked
          method: get
          cors: true

custom:
  customDomain:
    certificateName: holdr.fi
    domainName: api.holdr.fi
    basePath: 'analytics-mumbai'
    stage: ${self:provider.stage}
    createRoute53Record: true
