service: holdr-lbp-api
frameworkVersion: '3'	
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-domain-manager

provider:
  name: aws
  stage: dev
  region: us-west-2
  stackName: holdr-lbp-api
  runtime: nodejs14.x

functions:
  getLBPEndTime:
    handler: src/handlers.getLBPEndTimeHandler
    events:
      - http:
          path: time
          method: get
          cors: true
  getLBPprice:
    handler: src/handlers.getLBPPriceHandler
    events:
      - http:
          path: price
          method: get
          cors: true

	
custom:
  customDomain:
    certificateName: holdr.fi
    domainName: api.holdr.fi
    basePath: 'lbp'
    stage: ${self:provider.stage}
    createRoute53Record: true
